version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

    steps:
      - add_ssh_keys:
          fingerprints:
            - "8d:37:05:a6:7a:cf:61:1b:2d:77:96:9c:22:83:50:87"

      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install jsmin

      - run:
          name: update pac files
          command: |
            . venv/bin/activate
            python3 flora_pac
            git config user.email "zlx220000@msn.com"
            git config user.name "zmz125000"
            git add -A 
            git commit -m "update pac [ci skip]"
            git push origin master

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master

    jobs:
      - build

  build-on-push:
    jobs:
      - build:
          filters:
            branches:
              only: master
